### ISSUE TITLE
on ubu 12.04: shelr play <filename>.json parser problem - in both ppa and gem installs

### ISSUE THREAD

**Issue by agrabauskas** [shelr/shelr#11]
happens in the version from the ppa:
# 

root@puppet:~# shelr version
0.15.2
root@puppet:~# shelr play http://shelr.tv/records/4fa6cf8796608047c1000070.json
.==> Fetching http://shelr.tv/records/4fa6cf8796608047c1000070.json
/usr/lib/ruby/vendor_ruby/json/common.rb:148:in `parse': 745: unexpected token at '<!DOCTYPE html> (JSON::ParserError)
# <html>

also happens in the gem install:
# 

alleycat@vger:~$ shelr version
0.16.2
alleycat@vger:~$ shelr play http://shelr.tv/records/4fa6cf8796608047c1000070.json
.==> Fetching http://shelr.tv/records/4fa6cf8796608047c1000070.json
/var/lib/gems/1.8/gems/json-1.7.0/lib/json/common.rb:149:in `parse': 757: unexpected token at '<!DOCTYPE html> (JSON::ParserError)
# <html>

**Comment by antono** [comment]
Hm... not sure what was wrong. Just tried to reproduce it with PPA version

http://shelr.tv/records/4fb6840496608064fb00001e

No success :(
Make sure either record is public or you pass `access_key` with apropriate value.

**Comment by agrabauskas** [comment]
odd. it worked perfectly just now on both installations i have this time - a 0.15.2 where everything matched the outputs, and a 0.16.2 - even though i don't recall doing anything to either setup since posting that. i can only assume it was some error on my part or that perhaps some dependency got fixed by an apt-get update in the meantime. sorry for wasting your time.

**Comment by agrabauskas** [comment]
"matched the outputs from your recording" - i.e. the lsb_release -a, etc.

**Comment by antono** [comment]
@agrabauskas you are welcome :) no worries about my time.
