### ISSUE TITLE
No audio in shelr.tv

### ISSUE THREAD

**Issue by baldrailers** [shelr/shelr#12]
recording with `shelr record --sound` it's working great in my local machine, but when I push it to shelr.tv, i can't seem to hear any sound at all.

**Comment by antono** [comment]
Yep. It's not implemented yet :)

**Comment by arcfide** [comment]
I would like to have it implemented. :-)

**Comment by hazybluedot** [comment]
Any progress on this? I would like to record some screencasts for a programming class I teach, having the audio would be great!

**Comment by stefanschmidt** [comment]
Yeah, it would be really nice if the audio feature worked online. I guess many people would be happy to have a more sane way of offering moderated text screencasts than – yikes – youtube.
