### ISSUE TITLE
Play a recording locally without publishing it?

### ISSUE THREAD

**Issue by dpashkevich** [shelr/shelr#20]
Hi! Is it possible?

**Comment by EmilyVoukelatou** [comment]
Yes! Just `shelr record` and then `shelr play last` (or shelr play RECORDING_ID).

**Comment by dpashkevich** [comment]
Sorry, I didn't try out the tool before asking. The impression I got from the `README` is that shelr only works with `shelr.tv` website cause there's no word about playing files locally or sending the recordings to other people directly.
